package model;

public enum Form {
    PARTICIPIOPRESENTO,
    PARTICIPIOPRETERITO,
    INDICATIVOPRESENTO,
    INDICATIVOPRETERITO,
    IDICATIVOIMPERFECTO,
    INDICATIVOCONDICIONAL,
    INDICATIVOFUTURO,
    SUBJUNTIVOPRESENTO,
    SUBJUNTIVOIMPERFECTO,
    SUBJUNTIVOFUTURO,
    IMPERATIVOAFFIRMATIVO,
    IMPERATIVONEGATIVO
}
