SELECT DISTINCT
"Verbo".*,
"[GROUP_TABLE]"."VerbID",
[FORMS_AND_PRONOUNS]
""
FROM "Verbo"
INNER JOIN "[GROUP_TABLE]" ON "[GROUP_TABLE]"."VerbID" = "Verbo"."ID"
[FORM_INNER_JOINS]
ORDER BY RANDOM()
LIMIT [AMOUNT];